#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $AUTH_DB_NAME;
    CREATE DATABASE $CUSTOMER_DB_NAME;
    CREATE DATABASE $PRODUCT_DB_NAME;
    CREATE DATABASE $INTERACTION_DB_NAME;
EOSQL