"""Init product schema

Revision ID: 2a8548ba96f5
Revises: 
Create Date: 2025-11-07 03:49:27.214655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8548ba96f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('cd_product', sa.UUID(), nullable=False),
    sa.Column('ds_product_name', sa.String(length=255), nullable=False),
    sa.Column('ds_product_description', sa.Text(), nullable=True),
    sa.Column('vr_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_product_type', sa.Enum('produto', 'servico', name='producttype'), nullable=False),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cd_product')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_ds_product_name'), ['ds_product_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_ds_product_name'))

    op.drop_table('product')
    # ### end Alembic commands ###
