"""Init auth schema

Revision ID: c99312a17d59
Revises: 
Create Date: 2025-11-07 03:49:22.713918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99312a17d59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('cd_user', sa.UUID(), nullable=False),
    sa.Column('ds_user', sa.String(length=255), nullable=False),
    sa.Column('ds_user_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cd_user')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ds_user_email'), ['ds_user_email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ds_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
