"""Init customer schema

Revision ID: 8775c592f2d6
Revises: 
Create Date: 2025-11-07 03:49:25.430157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8775c592f2d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('cd_customer', sa.UUID(), nullable=False),
    sa.Column('ds_customer_name', sa.String(length=255), nullable=False),
    sa.Column('ds_customer_email', sa.String(length=255), nullable=False),
    sa.Column('ds_customer_phone', sa.String(length=20), nullable=True),
    sa.Column('ds_customer_cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('ds_customer_address', sa.String(length=500), nullable=True),
    sa.Column('ds_customer_city', sa.String(length=100), nullable=True),
    sa.Column('ds_customer_state', sa.String(length=2), nullable=True),
    sa.Column('ds_customer_zip_code', sa.String(length=10), nullable=True),
    sa.Column('ds_customer_country', sa.String(length=100), nullable=True),
    sa.Column('dt_customer_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_customer_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_customer_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cd_customer'),
    sa.UniqueConstraint('ds_customer_cpf_cnpj')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_ds_customer_email'), ['ds_customer_email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_ds_customer_email'))

    op.drop_table('customer')
    # ### end Alembic commands ###
